# The URL the site will be built for
base_url = "https://datavirke.dk"

# Used in RSS by default
title = "Datavirke"
description = "IT Consultancy specializing in DevOps, Cloud Infrastructure & Software Development"
# The default language, used in RSS
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hermit_zola"

taxonomies = [
           {name = "tags", rss = true}
]

generate_feed = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
render_emoji = true

[extra]
home_subtitle = "Software built well."
logo = "logo.svg"
footer_copyright = ' &mdash; CVR: 43033336'

hermit_menu = [
    { link = "/about", name = "About" },
    { link = "/experience", name = "Experience" },
    { link = "/posts", name = "Blog" },
]

hermit_social = [
    { name = "github", link = "https://github.com/MathiasPius" },
    { name = "linkedin", link = "https://www.linkedin.com/in/mathias-pius/" },
    { name = "email", link = "mailto:mathias@datavirke.dk" },
    { name = "twitter", link = "https://fosstodon.org/@MathiasPius" }
]

[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

[extra.author]
name = "Mathias Pius"
email = "mathias@datavirke.dk"
