# The URL the site will be built for
base_url = "https://datavirke.dk"

# Used in RSS by default
title = "Datavirke"
description = "Datavirke Description"
# The default language, used in RSS
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hermit_zola"

taxonomies = [
           {name = "tags", rss = true}
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
home_subtitle = "Software built well."
logo = "logo.svg"
footer_copyright = ''

hermit_menu = [
    { link = "/about", name = "About" },
]

hermit_social = [
    { name = "github", link = "https://github.com/MathiasPius" },
    { name = "linkedin", link = "https://www.linkedin.com/in/mathias-pius/" },
    { name = "email", link = "mailto:mathias@datavirke.dk" }
]

[extra.highlightjs]
enable = true
clipboard = true
theme = "vs2015"

[extra.author]
name = "Mathias Pius"
email = "mathias@datavirke.dk"