# On every push this script is executed
on:
  push:
    branches:
      - main

name: build static web server container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: checkout
        uses: actions/checkout@v2

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            registry.kronform.pius.dev/datavirke.dk/datavirke.dk
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: registry.kronform.pius.dev
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_SECRET }}

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
