# On every push this script is executed
on:
  push:
    branches:
      - main

name: build static web server container
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/kubi-zone/kubizone
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=sha

      - name: build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
