# On every push this script is executed
on:
  push:
    branches:
      - main

name: build and deploy to github pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build and deploy
        uses: shalzz/zola-deploy-action@v0.15.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}